# This is a basic workflow to help you get started with Actions

name: deploy-storage
on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

env:
  AZ_RG_Name: RG3
  AZ_RG_Location: WestEurope

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  deploy:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
      - name: Sign in to Azure
        uses: azure/login@v1
        with:
          client-id: ${{secrets.AZ_CLIENT_ID}}
          subscription-id: ${{secrets.AZ_SUB_ID}}
          tenant-id: ${{secrets.AZ_TENANT_ID}}
      - name: create resource group 
        uses: azure/cli@v1
        with:
          inlineScript:
            az group create --name ${{env.AZ_RG_Name}} --location ${{env.AZ_RG_Location}}
      - name: deploy storage 
        uses: azure/arm-deploy@v1
        with:
          deploymentName: ${{github.run_Number}}
          resourceGroupName: ${{env.AZ_RG_Name}}
          template: ./storage.bicep
       
